### ISSUE TITLE
Estamos  tendo problema para subir o flask

### ISSUE THREAD

**Issue by Cepesp-Fgv** [x8lucas8x/macroscopio-eleitoral#1]
AttributeError: 'module' object has no attribute 'lru_cache'

**Comment by x8lucas8x** [comment]
@Cepesp-Fgv lru_cache eh parte da biblioteca padrão de Python 3 e permite que request já feitas sejam servidas mais rapidamente, dado que estarão cacheadas. Fizemos uso de Python 3 pois o suporte a Python 2 será descontinuado em 2020. Alem disso, varias de nossas dependências como pandas e numpy já possuem roadmaps para descontinuar o suporte a Python 2 antes disso. Logo sugiro tentar novamente com Python 3. Lembre-se de instalar nossas dependências com o pip3, antes de tentar executar nosso código, assim como recomendado no nosso README.
